# Generated by Django 5.2.7 on 2025-10-21 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("warehouses", "0002_warehouse_latitude_warehouse_longitude"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("shopkeeper_to_warehouse", "Shopkeeper to Warehouse"),
                            ("warehouse_to_rider", "Warehouse to Rider"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="External payment gateway reference or internal transaction ID",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Distance in kilometers for rider payout calculation",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        default="mock",
                        help_text="Payment method: mock, cash, card, upi, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional transaction notes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="orders.order",
                    ),
                ),
                (
                    "payee",
                    models.ForeignKey(
                        help_text="User receiving the payment (warehouse admin or rider)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payer",
                    models.ForeignKey(
                        help_text="User making the payment (shopkeeper or warehouse admin)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        blank=True,
                        help_text="Rider receiving payout (only for warehouse_to_rider payments)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rider_payouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="warehouses.warehouse",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "payment_type"],
                        name="payments_pa_status_3728e3_idx",
                    ),
                    models.Index(
                        fields=["order"], name="payments_pa_order_i_1d1c93_idx"
                    ),
                    models.Index(
                        fields=["warehouse"], name="payments_pa_warehou_f69eb2_idx"
                    ),
                    models.Index(
                        fields=["rider"], name="payments_pa_rider_i_f5865c_idx"
                    ),
                ],
            },
        ),
    ]
