#!/bin/bash
# Quick Reference: Stockway Infrastructure Utilities
# =================================================

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║          Stockway Infrastructure Quick Reference             ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "📍 HEALTH ENDPOINT"
echo "   URL: GET /health/"
echo "   Response: {\"status\": \"ok\"}"
echo "   Test: curl http://127.0.0.1:8000/health/"
echo ""
echo "🤖 GITHUB ACTIONS"
echo "   Location: .github/workflows/ping.yml"
echo "   Schedule: Every 25 minutes"
echo "   Target: https://stockway.onrender.com/health/"
echo ""
echo "🚀 LOCAL DEVELOPMENT"
echo "   Command: ./run_local.sh"
echo "   Services:"
echo "     - Django backend (port 8000)"
echo "     - Celery worker + beat"
echo "     - Redis (auto-starts)"
echo "     - RabbitMQ (checks status)"
echo "     - Frontend (port 5173)"
echo "   Stop: Press Ctrl+C"
echo ""
echo "📁 LOG FILES"
echo "   - logs/django_local.log"
echo "   - logs/celery_local.log"
echo "   - logs/celery_beat_local.log"
echo "   - logs/frontend_local.log"
echo ""
echo "📚 DOCUMENTATION"
echo "   - INFRASTRUCTURE.md (detailed guide)"
echo "   - IMPLEMENTATION_SUMMARY.md (what was built)"
echo ""
echo "✅ QUICK START"
echo "   1. Ensure Redis and RabbitMQ are running"
echo "   2. Run: ./run_local.sh"
echo "   3. Access:"
echo "      - Backend: http://127.0.0.1:8000"
echo "      - Frontend: http://localhost:5173"
echo "      - Health: http://127.0.0.1:8000/health/"
echo ""
echo "═══════════════════════════════════════════════════════════════"
