# Generated by Django 5.2.8 on 2026-01-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_add_deleted_at_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
