# Generated by Django 5.2.8 on 2026-01-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_add_profile_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Approval"),
                    ("SHOPKEEPER", "Shopkeeper"),
                    ("RIDER", "Rider"),
                    ("WAREHOUSE_MANAGER", "Warehouse Manager"),
                    ("ADMIN", "Admin"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
