# Generated by Django 5.2.7 on 2025-10-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="supabase_uid",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Supabase Auth UID for JWT authentication",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
