# Generated by Django 5.2.7 on 2025-10-23 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_user_supabase_uid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shopkeeperprofile",
            options={
                "verbose_name": "Shopkeeper Profile",
                "verbose_name_plural": "Shopkeeper Profiles",
            },
        ),
        migrations.AddField(
            model_name="shopkeeperprofile",
            name="address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="shopkeeperprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="shopkeeperprofile",
            name="gst_number",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="shopkeeperprofile",
            name="license_number",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="shopkeeperprofile",
            name="onboarding_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shopkeeperprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="shopkeeperprofile",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shopkeeperprofile",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shopkeeperprofile",
            name="shop_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
