# Generated by Django 5.2.7 on 2025-11-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_enable_rls_inventory"),
        ("warehouses", "0005_warehousenotification_warehouse_contact_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Item category for classification",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="image_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL to item image in Supabase Storage",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="low_stock_threshold",
            field=models.PositiveIntegerField(
                default=10, help_text="Alert when stock falls below this level"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="stock_quantity",
            field=models.PositiveIntegerField(
                default=0, help_text="Current stock quantity"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["warehouse", "category"], name="inventory_i_warehou_9fe840_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["sku"], name="inventory_i_sku_3e99d5_idx"),
        ),
    ]
