# Generated by Django 5.2.8 on 2026-01-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inventory",
            "0003_remove_item_sku_remove_item_updated_at_item_category_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="sku",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="item",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
