# Generated by Django 5.2.8 on 2026-01-11 00:00
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_item_sku_item_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="image_urls",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
