# Generated by Django 5.2.7 on 2025-11-07 08:23

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("riders", "0002_enable_rls_riders"),
        ("warehouses", "0006_riderpayout_alter_warehouse_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="riderprofile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="riderprofile",
            name="warehouse",
        ),
        migrations.CreateModel(
            name="Rider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("busy", "Busy"),
                            ("inactive", "Inactive"),
                        ],
                        db_index=True,
                        default="available",
                        help_text="Current availability status of the rider",
                        max_length=20,
                    ),
                ),
                (
                    "current_location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        geography=True,
                        help_text="Current GPS location of the rider",
                        null=True,
                        srid=4326,
                    ),
                ),
                (
                    "total_earnings",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total earnings accumulated by the rider",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User account for the rider",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rider_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        help_text="Warehouse where rider is assigned",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="riders",
                        to="warehouses.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "riders",
                "ordering": ["-created_at"],
            },
        ),
    ]
