# Generated by Django 5.2.7 on 2025-11-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("riders", "0003_remove_riderprofile_user_and_more"),
        ("warehouses", "0007_alter_riderpayout_rider"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RiderProfile",
        ),
        migrations.AddIndex(
            model_name="rider",
            index=models.Index(
                fields=["warehouse", "status"], name="riders_warehou_b8597d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rider",
            index=models.Index(fields=["status"], name="riders_status_441554_idx"),
        ),
        migrations.AddIndex(
            model_name="rider",
            index=models.Index(fields=["user"], name="riders_user_id_17cd1f_idx"),
        ),
        migrations.AddConstraint(
            model_name="rider",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_earnings__gte", 0)),
                name="rider_total_earnings_non_negative",
            ),
        ),
    ]
