# Generated by Django 5.2.7 on 2025-10-23 04:00

import django.contrib.gis.db.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouses", "0002_warehouse_latitude_warehouse_longitude"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                geography=True,
                help_text="Geographic location (longitude, latitude)",
                null=True,
                srid=4326,
            ),
        ),
        migrations.AddIndex(
            model_name="warehouse",
            index=models.Index(
                fields=["location"], name="warehouses__locatio_25829d_idx"
            ),
        ),
    ]
