# Generated by Django 5.2.7 on 2025-11-05 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouses", "0004_enable_rls_warehouses"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WarehouseNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("order_received", "Order Received"),
                            ("low_stock", "Low Stock Alert"),
                            ("order_accepted", "Order Accepted"),
                            ("order_rejected", "Order Rejected"),
                            ("delivery_assigned", "Delivery Assigned"),
                            ("delivery_completed", "Delivery Completed"),
                            ("payment_received", "Payment Received"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data like order_id, item_id, etc.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="warehouse",
            name="contact_number",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Warehouse active status, requires admin approval",
            ),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="is_approved",
            field=models.BooleanField(default=False, help_text="Admin approval status"),
        ),
        migrations.AddIndex(
            model_name="warehouse",
            index=models.Index(
                fields=["is_active", "is_approved"],
                name="warehouses__is_acti_1e9db9_idx",
            ),
        ),
        migrations.AddField(
            model_name="warehousenotification",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="warehouses.warehouse",
            ),
        ),
        migrations.AddIndex(
            model_name="warehousenotification",
            index=models.Index(
                fields=["warehouse", "is_read"], name="warehouses__warehou_1ad559_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warehousenotification",
            index=models.Index(
                fields=["notification_type"], name="warehouses__notific_6b6231_idx"
            ),
        ),
    ]
