# Generated by Django 5.2.7 on 2025-11-05 15:50

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_enable_rls_orders"),
        ("riders", "0002_enable_rls_riders"),
        ("warehouses", "0005_warehousenotification_warehouse_contact_number_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RiderPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "distance_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payment_reference", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "rider_payouts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="warehouse",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="warehouse",
            name="warehouses__locatio_25829d_idx",
        ),
        migrations.RenameIndex(
            model_name="warehouse",
            new_name="warehouses_is_acti_3de84b_idx",
            old_name="warehouses__is_acti_1e9db9_idx",
        ),
        migrations.RenameIndex(
            model_name="warehousenotification",
            new_name="warehouse_n_warehou_77bf43_idx",
            old_name="warehouses__warehou_1ad559_idx",
        ),
        migrations.RenameIndex(
            model_name="warehousenotification",
            new_name="warehouse_n_notific_4e9a30_idx",
            old_name="warehouses__notific_6b6231_idx",
        ),
        migrations.RemoveField(
            model_name="warehouse",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="warehouse",
            name="longitude",
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="contact_number",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="warehousenotification",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="warehousenotification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("order", "Order"),
                    ("stock", "Stock"),
                    ("general", "General"),
                    ("payment", "Payment"),
                    ("rider", "Rider"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="warehouse",
            index=models.Index(fields=["admin"], name="warehouses_admin_i_f8d420_idx"),
        ),
        migrations.AlterModelTable(
            name="warehouse",
            table="warehouses",
        ),
        migrations.AlterModelTable(
            name="warehousenotification",
            table="warehouse_notifications",
        ),
        migrations.AddField(
            model_name="riderpayout",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rider_payouts",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="riderpayout",
            name="rider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payouts",
                to="riders.riderprofile",
            ),
        ),
        migrations.AddField(
            model_name="riderpayout",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rider_payouts",
                to="warehouses.warehouse",
            ),
        ),
        migrations.AddIndex(
            model_name="riderpayout",
            index=models.Index(
                fields=["warehouse", "status"], name="rider_payou_warehou_49c868_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="riderpayout",
            index=models.Index(
                fields=["rider", "status"], name="rider_payou_rider_i_04327c_idx"
            ),
        ),
    ]
