# Generated by Django 5.2.7 on 2025-11-07 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("riders", "0003_remove_riderprofile_user_and_more"),
        ("warehouses", "0006_riderpayout_alter_warehouse_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riderpayout",
            name="rider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payouts",
                to="riders.rider",
            ),
        ),
    ]
